### ISSUE TITLE
启动时崩溃

### ISSUE THREAD

**Issue by SinusoidalC** [MorphismMC/Epimorphism-Core#2]
[crash-2023-12-09_18.03.03-client.txt](https://github.com/GregTech-Chinese-Community/EPCore/files/13623738/crash-2023-12-09_18.03.03-client.txt)
CEu版本2.8.2

**Comment by gate-guardian** [comment]
目前仅支持GTCEu2.7.x，EPcore在1.12的开发工作已经停止，项目将迁移到1.20以支持GTM。抱歉！
